root: true
env:
  es2021: true
  node: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  semi:
    - error
    - never
  indent:
    - error
    - 2
    - SwitchCase: 1
  space-infix-ops:
    - error
  space-before-blocks:
    - error
  keyword-spacing:
    - error
  func-call-spacing:
    - error
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  arrow-spacing:
    - error
